/**
 * TeleDrive - Telegram Client Library
 * Handles all Telegram MTProto operations using GramJS
 */

// Use single import from main package which is browser-compatible
import { TelegramClient, Api } from 'telegram'
import { StringSession } from 'telegram/sessions'
import { CustomFile } from 'telegram/client/uploads'
import localforage from 'localforage'

// Storage keys
const SESSION_KEY = 'teledrive_session'
const ACCOUNTS_KEY = 'teledrive_accounts'
const CREDENTIALS_KEY = 'teledrive_credentials'

// Telegram DC server addresses (same in all clients)
const DC_ADDRESSES = {
    1: '149.154.175.53',
    2: '149.154.167.51',
    3: '149.154.175.100',
    4: '149.154.167.92',
    5: '91.108.56.190',
}
const DC_PORT = 443

/**
 * Detect whether a session string was generated by Pyrogram.
 * Pyrogram sessions are base64url strings that decode to exactly 351 bytes (v1)
 * or 356 bytes (v2 with int64 user_id). GramJS sessions are much longer.
 */
function isPyrogramSession(sessionStr) {
    try {
        const cleaned = sessionStr.trim()
        // Pyrogram sessions never contain '+' or '/' (they use base64url), and
        // their decoded length is 351 (v1: 1+256+4+1+1 + pad) or similar small sizes.
        const base64 = cleaned.replace(/-/g, '+').replace(/_/g, '/')
        const padded = base64 + '=='.slice((base64.length % 4 === 0) ? 4 : base64.length % 4)
        const bytes = Uint8Array.from(atob(padded), c => c.charCodeAt(0))
        // Pyrogram v1: 1+256+4+1 = 262 bytes, v2: 1+256+8+1 = 266 bytes
        // (Some builds add padding to reach 351/356 after base64)
        // Key heuristic: GramJS sessions decode to >300 bytes and start with \x01
        // Pyrogram sessions are much smaller OR start with a DC id byte (1-5)
        if (bytes.length < 300 && bytes[0] >= 1 && bytes[0] <= 5) {
            return true
        }
        // Also check if the decoded content looks like a Pyrogram session
        // by verifying the DC byte is valid and auth key area is non-zero
        if (bytes.length >= 262 && bytes[0] >= 1 && bytes[0] <= 5) {
            return true
        }
        return false
    } catch {
        return false
    }
}

/**
 * Convert a Pyrogram StringSession to a GramJS StringSession string.
 *
 * Pyrogram v1 format (262 bytes):
 *   [0]      dc_id       (uint8)
 *   [1..256] auth_key    (256 bytes)
 *   [257..260] user_id   (uint32 big-endian)
 *   [261]    is_bot      (uint8)
 *
 * Pyrogram v2 format (266 bytes):
 *   [0]      dc_id       (uint8)
 *   [1..256] auth_key    (256 bytes)
 *   [257..264] user_id   (uint64 big-endian)
 *   [265]    is_bot      (uint8)
 *
 * GramJS StringSession internal format (before base64):
 *   [0..1]   dc_id       (uint16 BE)
 *   [2..3]   ip_len      (uint16 BE)
 *   [4..N]   ip_address  (utf-8 bytes)
 *   [N+1..N+2] port      (uint16 BE)
 *   [N+3..N+258] auth_key (256 bytes)
 *
 * Then the whole buffer is base64url-encoded with a leading "1" version prefix.
 */
function convertPyrogramToGramjs(pyrogramSession) {
    const cleaned = pyrogramSession.trim()
    // Decode from base64url
    const base64 = cleaned.replace(/-/g, '+').replace(/_/g, '/')
    const padded = base64 + '=='.slice((base64.length % 4 === 0) ? 4 : base64.length % 4)
    const bytes = Uint8Array.from(atob(padded), c => c.charCodeAt(0))

    const dcId = bytes[0]
    const authKey = bytes.slice(1, 257)       // 256 bytes

    const ip = DC_ADDRESSES[dcId]
    if (!ip) {
        throw new Error(`Unknown DC ID ${dcId} in Pyrogram session. Valid DCs are 1-5.`)
    }

    const ipBytes = new TextEncoder().encode(ip)
    const ipLen = ipBytes.length

    // Build GramJS buffer: dc(2) + ipLen(2) + ip(ipLen) + port(2) + authKey(256)
    const totalLen = 2 + 2 + ipLen + 2 + 256
    const buf = new Uint8Array(totalLen)
    const view = new DataView(buf.buffer)

    view.setUint16(0, dcId, false)          // BE
    view.setUint16(2, ipLen, false)          // BE
    buf.set(ipBytes, 4)                      // ip string
    view.setUint16(4 + ipLen, DC_PORT, false) // port BE
    buf.set(authKey, 4 + ipLen + 2)          // auth key

    // Base64url encode
    let b64 = btoa(String.fromCharCode(...buf))
    b64 = b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '')

    // GramJS StringSession.save() prepends "1" as a version marker
    return '1' + b64
}

/**
 * Detect session type and normalise to GramJS format.
 * Returns { session, converted, type } where type is 'gramjs' | 'pyrogram'
 */
export function normaliseSession(sessionStr) {
    const s = sessionStr.trim()
    if (isPyrogramSession(s)) {
        const converted = convertPyrogramToGramjs(s)
        return { session: converted, converted: true, type: 'pyrogram' }
    }
    return { session: s, converted: false, type: 'gramjs' }
}

// Create localforage instance for auth data
const authStorage = localforage.createInstance({
    name: 'TeleDrive',
    storeName: 'auth'
})

// Migrate data from localStorage to localforage (runs once)
const migrateFromLocalStorage = async () => {
    try {
        // Check if migration already done
        const migrated = await authStorage.getItem('_migrated')
        if (migrated) return

        // Migrate session
        const oldSession = localStorage.getItem(SESSION_KEY)
        if (oldSession) {
            await authStorage.setItem(SESSION_KEY, oldSession)
            localStorage.removeItem(SESSION_KEY)
        }

        // Migrate accounts
        const oldAccounts = localStorage.getItem(ACCOUNTS_KEY)
        if (oldAccounts) {
            await authStorage.setItem(ACCOUNTS_KEY, JSON.parse(oldAccounts))
            localStorage.removeItem(ACCOUNTS_KEY)
        }

        // Mark migration as complete
        await authStorage.setItem('_migrated', true)
        console.log('TeleDrive: Auth data migrated to IndexedDB')
    } catch (e) {
        console.warn('Migration from localStorage failed:', e)
    }
}

// Run migration on load
migrateFromLocalStorage()

class TelegramService {
    constructor() {
        this.client = null
        this.session = null
        this.currentAccount = null
        this.apiId = null
        this.apiHash = null
    }

    /**
     * Save API credentials to IndexedDB
     */
    async saveCredentials(apiId, apiHash) {
        try {
            await authStorage.setItem(CREDENTIALS_KEY, { apiId: Number(apiId), apiHash: String(apiHash) })
            this.apiId = Number(apiId)
            this.apiHash = String(apiHash)
        } catch (e) {
            console.error('Failed to save credentials:', e)
        }
    }

    /**
     * Load API credentials from IndexedDB
     */
    async loadCredentials() {
        try {
            const creds = await authStorage.getItem(CREDENTIALS_KEY)
            if (creds && creds.apiId && creds.apiHash) {
                this.apiId = creds.apiId
                this.apiHash = creds.apiHash
                return creds
            }
            return null
        } catch {
            return null
        }
    }

    /**
     * Clear saved API credentials
     */
    async clearCredentials() {
        try {
            await authStorage.removeItem(CREDENTIALS_KEY)
            this.apiId = null
            this.apiHash = null
        } catch (e) {
            console.error('Failed to clear credentials:', e)
        }
    }

    /**
     * Build client instance without connecting.
     * Call connect() separately only when you have a real session string.
     */
    _buildClient(sessionString = '') {
        if (this.client) {
            try { this.client.disconnect() } catch { /* ignore */ }
            this.client = null
        }

        this.session = new StringSession(sessionString)

        this.client = new TelegramClient(
            this.session,
            this.apiId,
            this.apiHash,
            {
                connectionRetries: 3,
                useWSS: true,
                retryDelay: 1000,
            }
        )

        // Silence GramJS internal logger after construction
        try {
            if (this.client._log) this.client._log.setLevel('none')
        } catch { /* ignore */ }

        return this.client
    }

    /**
     * Initialize the Telegram client.
     * Only connects when sessionString is non-empty — an empty string means
     * "just build the client so sendCode() can be called later", which avoids
     * the full MTProto key-exchange that hangs in a browser with no session.
     */
    async init(sessionString = '', credentials = null) {
        // Resolve credentials: argument > instance > stored
        if (credentials && credentials.apiId && credentials.apiHash) {
            this.apiId = Number(credentials.apiId)
            this.apiHash = String(credentials.apiHash)
        } else if (!this.apiId || !this.apiHash) {
            await this.loadCredentials()
        }

        if (!this.apiId || !this.apiHash) {
            throw new Error('API credentials not set. Please enter your API ID and API Hash.')
        }

        this._buildClient(sessionString)

        // Only attempt to connect when we have an actual session.
        // An empty session would trigger a full key-exchange which hangs in browser.
        if (sessionString && sessionString.length > 10) {
            await Promise.race([
                this.client.connect(),
                new Promise((_, reject) =>
                    setTimeout(() => reject(new Error('Connection timeout — check your internet connection.')), 20000)
                )
            ])
        }

        return this.client
    }

    /**
     * Connect for the first time (phone login flow).
     * Called internally by sendCode() before making the first API call.
     */
    async _ensureConnected() {
        if (!this.client) throw new Error('Client not built — call init() first')
        if (this.client.connected) return
        await Promise.race([
            this.client.connect(),
            new Promise((_, reject) =>
                setTimeout(() => reject(new Error('Connection timeout — check your internet connection.')), 20000)
            )
        ])
    }

    /**
     * Check if user is authenticated.
     */
    async isAuthenticated() {
        if (!this.client) return false
        try {
            return await this.client.isUserAuthorized()
        } catch {
            return false
        }
    }

    /**
     * Start authentication with phone number
     */
    async sendCode(phoneNumber) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        // For phone flow, client was built without connecting — connect now
        await this._ensureConnected()

        const result = await this.client.sendCode(
            {
                apiId: this.apiId,
                apiHash: this.apiHash,
            },
            phoneNumber
        )

        return result
    }

    /**
     * Complete authentication with code
     */
    async signIn(phoneNumber, phoneCode, phoneCodeHash) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        try {
            const result = await this.client.invoke(
                new Api.auth.SignIn({
                    phoneNumber,
                    phoneCodeHash,
                    phoneCode,
                })
            )

            // Save session
            const sessionString = this.session.save()
            this.saveSession(sessionString)

            return result
        } catch (error) {
            if (error.errorMessage === 'SESSION_PASSWORD_NEEDED') {
                throw { type: '2FA_REQUIRED', error }
            }
            throw error
        }
    }

    /**
     * Complete 2FA authentication
     */
    async signInWith2FA(password) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const result = await this.client.signInWithPassword(
            {
                apiId: this.apiId,
                apiHash: this.apiHash,
            },
            {
                password: async () => password,
                onError: (err) => { throw err }
            }
        )

        // Save session
        const sessionString = this.session.save()
        this.saveSession(sessionString)

        return result
    }

    /**
     * Get current user info
     */
    async getMe() {
        if (!this.client) return null
        try {
            return await this.client.getMe()
        } catch {
            return null
        }
    }

    /**
     * Get messages from Saved Messages (self chat)
     */
    async getSavedMessages(limit = 100, offsetId = 0) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const messages = await this.client.getMessages('me', {
            limit,
            offsetId,
        })

        return messages
    }

    /**
     * Send a text message to Saved Messages (used for folder markers)
     */
    async sendMessage(text) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const result = await this.client.sendMessage('me', {
            message: text,
        })

        return result
    }

    /**
     * Send a file to Saved Messages
     */
    async sendFile(file, caption = '', progressCallback = null) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        // Convert browser File to ArrayBuffer for GramJS
        const arrayBuffer = await file.arrayBuffer()
        const buffer = Buffer.from(arrayBuffer)

        const result = await this.client.sendFile('me', {
            file: new CustomFile(file.name, file.size, '', buffer),
            caption,
            progressCallback,
            forceDocument: true,
        })

        return result
    }

    /**
     * Send a photo to Saved Messages
     */
    async sendPhoto(file, caption = '', progressCallback = null) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        // Convert browser File to ArrayBuffer for GramJS
        const arrayBuffer = await file.arrayBuffer()
        const buffer = Buffer.from(arrayBuffer)

        const result = await this.client.sendFile('me', {
            file: new CustomFile(file.name, file.size, '', buffer),
            caption,
            progressCallback,
            forceDocument: false,
        })

        return result
    }

    /**
     * Download media from a message
     */
    async downloadMedia(message, progressCallback = null) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const buffer = await this.client.downloadMedia(message, {
            progressCallback,
        })

        return buffer
    }

    /**
     * Get downloadable URL for streaming (for videos)
     */
    async getStreamUrl(message) {
        // GramJS doesn't provide direct streaming URLs
        // We'll need to download in chunks for streaming
        // This will be handled by the streaming component
        return null
    }

    /**
     * Edit message caption (for updating metadata)
     */
    async editMessageCaption(messageId, newCaption) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const result = await this.client.invoke(
            new Api.messages.EditMessage({
                peer: 'me',
                id: messageId,
                message: newCaption,
            })
        )

        return result
    }

    /**
     * Delete messages
     */
    async deleteMessages(messageIds) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const result = await this.client.invoke(
            new Api.messages.DeleteMessages({
                id: messageIds,
                revoke: true,
            })
        )

        return result
    }

    /**
     * Send a text message (for folder markers)
     */
    async sendMessage(text) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const result = await this.client.sendMessage('me', {
            message: text,
        })

        return result
    }

    /**
     * Search messages
     */
    async searchMessages(query, limit = 50) {
        if (!this.client) {
            throw new Error('Client not initialized')
        }

        const result = await this.client.invoke(
            new Api.messages.Search({
                peer: 'me',
                q: query,
                filter: new Api.InputMessagesFilterEmpty(),
                minDate: 0,
                maxDate: 0,
                offsetId: 0,
                addOffset: 0,
                limit,
                maxId: 0,
                minId: 0,
                hash: BigInt(0),
            })
        )

        return result.messages || []
    }

    /**
     * Save session to IndexedDB
     */
    async saveSession(sessionString) {
        try {
            await authStorage.setItem(SESSION_KEY, sessionString)
        } catch (e) {
            console.error('Failed to save session:', e)
        }
    }

    /**
     * Load session from IndexedDB
     */
    async loadSession() {
        try {
            return await authStorage.getItem(SESSION_KEY) || ''
        } catch {
            return ''
        }
    }

    /**
     * Clear session
     */
    async clearSession() {
        try {
            await authStorage.removeItem(SESSION_KEY)
        } catch (e) {
            console.error('Failed to clear session:', e)
        }
    }

    /**
     * Log out
     */
    async logout() {
        if (this.client) {
            try {
                await this.client.invoke(new Api.auth.LogOut())
            } catch (e) {
                console.error('Logout error:', e)
            }
        }
        await this.clearSession()
        this.client = null
        this.session = null
    }

    /**
     * Get all saved accounts
     */
    async getAccounts() {
        try {
            const accounts = await authStorage.getItem(ACCOUNTS_KEY)
            return accounts || []
        } catch {
            return []
        }
    }

    /**
     * Add account to saved accounts
     */
    async addAccount(account) {
        const accounts = await this.getAccounts()
        const exists = accounts.find(a => a.id === account.id)
        if (!exists) {
            accounts.push(account)
            await authStorage.setItem(ACCOUNTS_KEY, accounts)
        }
    }

    /**
     * Remove account from saved accounts
     */
    async removeAccount(accountId) {
        const accounts = await this.getAccounts()
        const filtered = accounts.filter(a => a.id !== accountId)
        await authStorage.setItem(ACCOUNTS_KEY, filtered)
    }

    /**
     * Switch to a different account
     */
    async switchAccount(sessionString) {
        await this.logout()
        await this.init(sessionString)
        return await this.isAuthenticated()
    }
}

// Singleton instance
const telegramService = new TelegramService()

export default telegramService
export { TelegramService }
